// <auto-generated />
using System;
using Dal.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElektrikDagıtım.Dal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Concrete.Muhasebe.BUTCE_BILGI", b =>
                {
                    b.Property<int>("ButceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ButceId"), 1L, 1);

                    b.Property<long>("Butce")
                        .HasColumnType("bigint");

                    b.HasKey("ButceId");

                    b.ToTable("BUTCE_BILGILERI");
                });

            modelBuilder.Entity("Entities.Concrete.Muhasebe.FATURA", b =>
                {
                    b.Property<int>("FaturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaturaId"), 1L, 1);

                    b.Property<int>("AboneId")
                        .HasColumnType("int");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<double>("FaturaBedeli")
                        .HasColumnType("float");

                    b.Property<string>("HizmetAdı")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kdv")
                        .HasColumnType("int");

                    b.Property<int?>("TahsilatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("FaturaId");

                    b.HasIndex("TahsilatId");

                    b.ToTable("FATURALAR");
                });

            modelBuilder.Entity("Entities.Concrete.Muhasebe.TAHSILAT", b =>
                {
                    b.Property<int>("TahsilatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TahsilatId"), 1L, 1);

                    b.Property<int>("AboneId")
                        .HasColumnType("int");

                    b.Property<string>("Acıklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KdvOncesiTutar")
                        .HasColumnType("int");

                    b.Property<decimal>("KdvOranı")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TahsilatTutari")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("TahsilatId");

                    b.ToTable("TAHSILATLAR");
                });

            modelBuilder.Entity("Entities.Concrete.Sistem.ABONE", b =>
                {
                    b.Property<int>("AboneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AboneId"), 1L, 1);

                    b.Property<DateTime?>("AbnKayıtTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("GsmNo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("YetkiId")
                        .HasColumnType("int");

                    b.HasKey("AboneId");

                    b.ToTable("ABONELER");
                });

            modelBuilder.Entity("Entities.Concrete.Sistem.ABONE_BORC", b =>
                {
                    b.Property<int>("AboneBorcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AboneBorcId"), 1L, 1);

                    b.Property<int>("AboneId")
                        .HasColumnType("int");

                    b.Property<double>("Borclar")
                        .HasColumnType("float");

                    b.HasKey("AboneBorcId");

                    b.ToTable("ABONE_BORCLARI");
                });

            modelBuilder.Entity("Entities.Concrete.Sistem.KULLANICI_YETKI", b =>
                {
                    b.Property<int>("YetkiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YetkiId"), 1L, 1);

                    b.Property<string>("YetkiAdı")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YetkiId");

                    b.ToTable("KULLANICI_YETKILERI");
                });

            modelBuilder.Entity("Entities.Concrete.Muhasebe.FATURA", b =>
                {
                    b.HasOne("Entities.Concrete.Muhasebe.TAHSILAT", null)
                        .WithMany("Faturalar")
                        .HasForeignKey("TahsilatId");
                });

            modelBuilder.Entity("Entities.Concrete.Muhasebe.TAHSILAT", b =>
                {
                    b.Navigation("Faturalar");
                });
#pragma warning restore 612, 618
        }
    }
}
